name: hs-elyonc
version: 0.1.0.0
github: "EidosX/Elyon"
license: MIT
author: "Diego Imbert"
maintainer: "diegoimbert@pm.me"
copyright: "2023 Diego Imbert"

description: Please see the README on GitHub at <https://github.com/EidosX/Elyon#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - indents
  - text

default-extensions:
  - OverloadedStrings
  - TupleSections

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  hs-elyonc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hs-elyonc

tests:
  hs-elyonc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hs-elyonc
